name: Build EXE
on: [push]
jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build EXE
        run: |
          npm install
          npm install electron-builder --save-dev
          npx electron-builder --win
           
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: My-Desktop-App
          path: dist/*.exe
